leftnav:
- identifier: 7d4a2f11-b597-81ce-42e1-a3451d59151f
  name: Syllabus
  pageRef: /pages/syllabus
  weight: 10
- identifier: 85deb539-cd28-5378-0d84-31da68a71a43
  name: Readings
  pageRef: /pages/readings
  weight: 20
- identifier: ec042a22-5a4d-73d5-2b3c-140035be6d5a
  name: Lecture Notes
  pageRef: /pages/lecture-notes
  weight: 30
- identifier: 4cf9a08a-0275-f957-365e-6967e64dc491
  name: Assignments
  pageRef: /pages/assignments
  weight: 40
- identifier: 41c5858c-2854-ef21-d89c-2470dc2bfea7
  name: Projects
  pageRef: /pages/projects
  weight: 50
